# Generated by Django 3.1.7 on 2021-12-23 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='thing',
            name='color',
        ),
        migrations.AddField(
            model_name='thing',
            name='name',
            field=models.CharField(default='Billy Bob', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='things', to='users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='core.color')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='core.shape')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='core.thing')),
            ],
        ),
    ]
